language: node_js

node_js:
  - "node"
  - "15.1.0"
  - "12.16.1"
  - "10.22.1"

before_script:
  - npm i . -g

script:
  - cd example
  - brickyard ls
  - brickyard ls backend-plan
  - brickyard test mocha backend-plan
  - brickyard build backend-plan --run
  - cd output
  - node .
