language: node_js

node_js:
  - "node"
  - "7.0.0"

before_script:
  - npm i . -g

script:
  - brickyard create-module buildtask brickyard_modules/build-test
  - echo "const brickyard=require('brickyard'); const gulp=require('gulp'); brickyard.ensureVersion('3.2.1'); gulp.task('a-build-task', ()=>console.log('building')); gulp.register_sub_tasks('build',0,'a-build-task'); gulp.task('a-run-task', ()=>brickyard.events.emit('run')); gulp.register_sub_tasks('run',0,'a-run-task');" > brickyard_modules/build-test/index.js
  - brickyard create-module plan brickyard_modules/plan-test
  - echo "module.exports={modules:['backend-test','build-test']}" > brickyard_modules/plan-test/index.js
  - brickyard create-module backend brickyard_modules/backend-test
  - echo "require('brickyard').events.on('run', ()=>console.log('running'))" > brickyard_modules/backend-test/index.js
  - brickyard ls
  - brickyard ls plan-test
  - brickyard build plan-test
  - brickyard run output
  - cd output
  - brickyard run .
  - cd ..
